### ISSUE TITLE
Suggestions on improving your manuscript and documentation.

### ISSUE THREAD

**Issue by Anjan-Purkayastha** [pierrepeterlongo/back_to_sequences#6]
This is a `Good Enhancement Suggestion`.
I have reviewed your manuscript. While it describes a general-purpose bioinformatics tool that may have many applications. it will be helpful if you provide an overview of your k-mer search method and specifically highlight **how your tool solves the problem of preserving the k-mer/parent sequence link**.  Afer all, this is the central claim of your paper and I as a user of your tool am interested in how you have solved this problem. This should be included in both your manuscript as well as your online documentation.
The second suggestion is a minor one. You mention some code run-times in Table 1 of your manuscript. **Please be specific as to which time (real/user) you are reporting.**

**Comment by pierrepeterlongo** [comment]
Hi @Anjan-Purkayastha 
Thanks a lot for your review and these suggestions. This will improve the manuscript and documentation.

**Comment by pierrepeterlongo** [comment]
Hello @Anjan-Purkayastha


> it will be helpful if you provide an overview of your k-mer search method and specifically highlight how your tool solves the problem of preserving the k-mer/parent sequence link.

This is now something that is proposed in the documentation: https://b2s-doc.readthedocs.io/en/latest/methods.html

> This should be included in both your manuscript as well as your online documentation.

This appears only in the documentation. This is due to the fact that
 - with respect to this [recommendation](https://github.com/openjournals/joss-reviews/issues/6872#issuecomment-2205642997), we decided to extract the documentation from the README of the main repo. 
 - reviewer @amoeba [suggested](https://github.com/pierrepeterlongo/back_to_sequences/issues/8) halving the size of the manuscript in order to comply with JOSS recommendations. Hence most of the paper content is now located in the [documentation](https://b2s-doc.readthedocs.io)

> You mention some code run-times in Table 1 of your manuscript. Please be specific as to which time (real/user) you are reporting.

This is now clearly indicated in the [bench result page](https://b2s-doc.readthedocs.io/en/latest/results.html#id1).


Thanks again for your suggestions
Pierre
